package com.zhiyi.chinaipo.models.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhiyi.chinaipo.models.db.StockCodeEntity;
import com.zhiyi.chinaipo.models.entity.articles.ArticlesCachedEntity;
import com.zhiyi.chinaipo.models.entity.auth.NicknameEntity;
import com.zhiyi.chinaipo.models.entity.auth.PortraitEntity;
import com.zhiyi.chinaipo.models.entity.news.NewsSave;
import com.zhiyi.chinaipo.models.entity.search.SearchSave;

import com.zhiyi.chinaipo.models.greendao.StockCodeEntityDao;
import com.zhiyi.chinaipo.models.greendao.ArticlesCachedEntityDao;
import com.zhiyi.chinaipo.models.greendao.NicknameEntityDao;
import com.zhiyi.chinaipo.models.greendao.PortraitEntityDao;
import com.zhiyi.chinaipo.models.greendao.NewsSaveDao;
import com.zhiyi.chinaipo.models.greendao.SearchSaveDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stockCodeEntityDaoConfig;
    private final DaoConfig articlesCachedEntityDaoConfig;
    private final DaoConfig nicknameEntityDaoConfig;
    private final DaoConfig portraitEntityDaoConfig;
    private final DaoConfig newsSaveDaoConfig;
    private final DaoConfig searchSaveDaoConfig;

    private final StockCodeEntityDao stockCodeEntityDao;
    private final ArticlesCachedEntityDao articlesCachedEntityDao;
    private final NicknameEntityDao nicknameEntityDao;
    private final PortraitEntityDao portraitEntityDao;
    private final NewsSaveDao newsSaveDao;
    private final SearchSaveDao searchSaveDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stockCodeEntityDaoConfig = daoConfigMap.get(StockCodeEntityDao.class).clone();
        stockCodeEntityDaoConfig.initIdentityScope(type);

        articlesCachedEntityDaoConfig = daoConfigMap.get(ArticlesCachedEntityDao.class).clone();
        articlesCachedEntityDaoConfig.initIdentityScope(type);

        nicknameEntityDaoConfig = daoConfigMap.get(NicknameEntityDao.class).clone();
        nicknameEntityDaoConfig.initIdentityScope(type);

        portraitEntityDaoConfig = daoConfigMap.get(PortraitEntityDao.class).clone();
        portraitEntityDaoConfig.initIdentityScope(type);

        newsSaveDaoConfig = daoConfigMap.get(NewsSaveDao.class).clone();
        newsSaveDaoConfig.initIdentityScope(type);

        searchSaveDaoConfig = daoConfigMap.get(SearchSaveDao.class).clone();
        searchSaveDaoConfig.initIdentityScope(type);

        stockCodeEntityDao = new StockCodeEntityDao(stockCodeEntityDaoConfig, this);
        articlesCachedEntityDao = new ArticlesCachedEntityDao(articlesCachedEntityDaoConfig, this);
        nicknameEntityDao = new NicknameEntityDao(nicknameEntityDaoConfig, this);
        portraitEntityDao = new PortraitEntityDao(portraitEntityDaoConfig, this);
        newsSaveDao = new NewsSaveDao(newsSaveDaoConfig, this);
        searchSaveDao = new SearchSaveDao(searchSaveDaoConfig, this);

        registerDao(StockCodeEntity.class, stockCodeEntityDao);
        registerDao(ArticlesCachedEntity.class, articlesCachedEntityDao);
        registerDao(NicknameEntity.class, nicknameEntityDao);
        registerDao(PortraitEntity.class, portraitEntityDao);
        registerDao(NewsSave.class, newsSaveDao);
        registerDao(SearchSave.class, searchSaveDao);
    }
    
    public void clear() {
        stockCodeEntityDaoConfig.clearIdentityScope();
        articlesCachedEntityDaoConfig.clearIdentityScope();
        nicknameEntityDaoConfig.clearIdentityScope();
        portraitEntityDaoConfig.clearIdentityScope();
        newsSaveDaoConfig.clearIdentityScope();
        searchSaveDaoConfig.clearIdentityScope();
    }

    public StockCodeEntityDao getStockCodeEntityDao() {
        return stockCodeEntityDao;
    }

    public ArticlesCachedEntityDao getArticlesCachedEntityDao() {
        return articlesCachedEntityDao;
    }

    public NicknameEntityDao getNicknameEntityDao() {
        return nicknameEntityDao;
    }

    public PortraitEntityDao getPortraitEntityDao() {
        return portraitEntityDao;
    }

    public NewsSaveDao getNewsSaveDao() {
        return newsSaveDao;
    }

    public SearchSaveDao getSearchSaveDao() {
        return searchSaveDao;
    }

}
